# Generated by Django 2.1.3 on 2018-11-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publication date'),
        ),
    ]
